#!/bin/bash
[ "$SDK_LOC" ] || SDK_LOC=/shared/fsl-imx-xwayland/5.10-hardknott
[ "$SDK_NAME" ] || SDK_NAME=cortexa53-crypto-poky-linux

[ ! -e "${SDK_LOC}/environment-setup-${SDK_NAME}" ] && {
    echo "Sorry, please verify: ${SDK_LOC}/environment-setup-${SDK_NAME}"
    exit 1
}

# shellcheck disable=SC1090
. "${SDK_LOC}/environment-setup-${SDK_NAME}"
#. ./environment-setup-${SDK_NAME}

SYSROOT="${SDK_LOC}/sysroots/${SDK_NAME}"
export PKG_CONFIG_SYSROOT_DIR="${SYSROOT}"
export PKG_CONFIG_PATH="${SYSROOT}/usr/lib/pkgconfig"
export PKG_CONFIG_DIR=''

#SYSROOT_COMPONENT=/opt/desktop/build-desktop/tmp/sysroots-components/cortexa53-crypto
#export GLIBS="-I${SYSROOT_COMPONENT}/glib-2.0/usr/include/glib-2.0 -I${SYSROOT_COMPONENT}/glib-2.0/usr/lib/glib-2.0/include"

make "$@"

