#ifndef RTSP_FRAME_ID_H
#define RTSP_FRAME_ID_H

#define RTSP_FRAME_ID_COUNTRY_CODE 0xff
#define RTSP_FRAME_ID_COUNTRY_EXTENSION 0xc1
#define RTSP_FRAME_ID_DATA_SIZE 28
#define RTSP_FRAME_ID_REGISTERED_PAYLOAD_SIZE 30
#define RTSP_FRAME_ID_MAGIC "GSTSYNC1"
#define RTSP_FRAME_ID_MAGIC_SIZE 8
#define RTSP_FRAME_ID_VERSION 1

#endif /* RTSP_FRAME_ID_H */
