name: Gemini Scheduled Issue Triage

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
      - 'release/**/*'
    paths:
      - '.github/workflows/gemini-scheduled-triage.yml'
  pull_request:
    branches:
      - main
      - 'release/**/*'
    paths:
      - '.github/workflows/gemini-scheduled-triage.yml'
  workflow_dispatch:

jobs:
  triage:
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    uses: jhw7500/automation/.github/workflows/gemini-scheduled-triage.yml@v1.22
    secrets: inherit
